Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Http\\Controllers\\AlquilerController",
            "name": "AlquilerController",
            "summary": "Controlador\u0020para\u0020gestionar\u0020alquileres\u0020de\u0020veh\u00EDculos.",
            "url": "classes/App-Http-Controllers-AlquilerController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AlquilerController\u003A\u003Amostrar\u0028\u0029",
            "name": "mostrar",
            "summary": "Muestra\u0020los\u0020detalles\u0020de\u0020la\u0020p\u00E1gina\u0020del\u0020Alquiler\u0020para\u0020el\u0020cliente\u0020autenticado.",
            "url": "classes/App-Http-Controllers-AlquilerController.html#method_mostrar"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AlquilerController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Guarda\u0020un\u0020nuevo\u0020alquiler\u0020en\u0020la\u0020base\u0020de\u0020datos.",
            "url": "classes/App-Http-Controllers-AlquilerController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AlquilerController\u003A\u003AmostrarAlquilerdela\u00F1o\u0028\u0029",
            "name": "mostrarAlquilerdela\u00F1o",
            "summary": "Muestra\u0020la\u0020lista\u0020de\u0020alquileres\u0020para\u0020el\u0020a\u00F1o\u0020actual.",
            "url": "classes/App-Http-Controllers-AlquilerController.html#method_mostrarAlquilerdela%C3%B1o"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AlquilerController\u003A\u003AobtenerAlquilerMensual\u0028\u0029",
            "name": "obtenerAlquilerMensual",
            "summary": "Devuelve\u0020la\u0020lista\u0020de\u0020alquileres\u0020para\u0020el\u0020a\u00F1o\u0020actual\u0020y\u0020el\u0020mes\u0020seleccionado\u0020presente\u0020en\u0020la\u0020base\u0020de\u0020datos.",
            "url": "classes/App-Http-Controllers-AlquilerController.html#method_obtenerAlquilerMensual"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AlquilerController\u003A\u003AmostrarAlquileresMensual\u0028\u0029",
            "name": "mostrarAlquileresMensual",
            "summary": "Muestra\u0020la\u0020lista\u0020de\u0020alquileres\u0020para\u0020el\u0020a\u00F1o\u0020actual\u0020y\u0020el\u0020mes\u0020seleccionado.",
            "url": "classes/App-Http-Controllers-AlquilerController.html#method_mostrarAlquileresMensual"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AlquilerController\u003A\u003AgetEstadisticas\u0028\u0029",
            "name": "getEstadisticas",
            "summary": "Muestra\u0020la\u0020p\u00E1gina\u0020con\u0020estad\u00EDsticas\u0020del\u0020n\u00FAmero\u0020total\u0020de\u0020alquileres\u0020para\u0020cada\u0020mes\u0020del\u0020a\u00F1o\u0020actual.",
            "url": "classes/App-Http-Controllers-AlquilerController.html#method_getEstadisticas"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController",
            "name": "ClienteController",
            "summary": "Controlador\u0020para\u0020gestionar\u0020clientes\u0020en\u0020la\u0020aplicaci\u00F3n.",
            "url": "classes/App-Http-Controllers-ClienteController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Muestra\u0020la\u0020lista\u0020de\u0020clientes\u0020con\u0020paginaci\u00F3n.",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Muestra\u0020el\u0020formulario\u0020de\u0020inicio\u0020de\u0020sesi\u00F3n.",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Guarda\u0020un\u0020nuevo\u0020cliente\u0020en\u0020la\u0020base\u0020de\u0020datos.",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003AeditProfile\u0028\u0029",
            "name": "editProfile",
            "summary": "Muestra\u0020la\u0020vista\u0020donde\u0020el\u0020cliente\u0020puede\u0020editar\u0020la\u0020informaci\u00F3n\u0020personal.",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_editProfile"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003AeditPassword\u0028\u0029",
            "name": "editPassword",
            "summary": "Muestra\u0020la\u0020vista\u0020donde\u0020el\u0020cliente\u0020puede\u0020cambiar\u0020su\u0020contrase\u00F1a.",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_editPassword"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003AupdateProfile\u0028\u0029",
            "name": "updateProfile",
            "summary": "Actualiza\u0020la\u0020informaci\u00F3n\u0020personal\u0020del\u0020cliente.",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_updateProfile"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003AupdatePassword\u0028\u0029",
            "name": "updatePassword",
            "summary": "Actualiza\u0020la\u0020contrase\u00F1a\u0020del\u0020cliente.",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_updatePassword"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003AupdateImage\u0028\u0029",
            "name": "updateImage",
            "summary": "Actualiza\u0020la\u0020foto\u0020de\u0020perfil\u0020del\u0020cliente.",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_updateImage"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003AdeleteSelected\u0028\u0029",
            "name": "deleteSelected",
            "summary": "Elimina\u0020los\u0020clientes\u0020seleccionados.",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_deleteSelected"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ClienteController\u003A\u003AdeleteAll\u0028\u0029",
            "name": "deleteAll",
            "summary": "Elimina\u0020todos\u0020los\u0020clientes.",
            "url": "classes/App-Http-Controllers-ClienteController.html#method_deleteAll"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpleadoController",
            "name": "EmpleadoController",
            "summary": "Controlador\u0020para\u0020gestionar\u0020empleados.",
            "url": "classes/App-Http-Controllers-EmpleadoController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpleadoController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Muestra\u0020la\u0020lista\u0020de\u0020empleados\u0020con\u0020paginaci\u00F3n.",
            "url": "classes/App-Http-Controllers-EmpleadoController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpleadoController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Muestra\u0020el\u0020formulario\u0020para\u0020crear\u0020un\u0020nuevo\u0020empleado.",
            "url": "classes/App-Http-Controllers-EmpleadoController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpleadoController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Guarda\u0020un\u0020nuevo\u0020empleado\u0020en\u0020la\u0020base\u0020de\u0020datos.",
            "url": "classes/App-Http-Controllers-EmpleadoController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpleadoController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Muestra\u0020el\u0020formulario\u0020para\u0020editar\u0020un\u0020empleado.",
            "url": "classes/App-Http-Controllers-EmpleadoController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpleadoController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Actualiza\u0020y\u0020guarda\u0020los\u0020nuevos\u0020datos\u0020del\u0020empleado.",
            "url": "classes/App-Http-Controllers-EmpleadoController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EmpleadoController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Elimina\u0020un\u0020empleado\u0020de\u0020la\u0020base\u0020de\u0020datos.",
            "url": "classes/App-Http-Controllers-EmpleadoController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\StorageController",
            "name": "StorageController",
            "summary": "Controlador\u0020para\u0020guardar\u0020archivos.",
            "url": "classes/App-Http-Controllers-StorageController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\StorageController\u003A\u003AstoreImage\u0028\u0029",
            "name": "storeImage",
            "summary": "Guarda\u0020una\u0020imagen.",
            "url": "classes/App-Http-Controllers-StorageController.html#method_storeImage"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\StorageController\u003A\u003AupdateImage\u0028\u0029",
            "name": "updateImage",
            "summary": "Actualiza\u0020una\u0020imagen.",
            "url": "classes/App-Http-Controllers-StorageController.html#method_updateImage"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\StorageController\u003A\u003AfindAndDeleteImage\u0028\u0029",
            "name": "findAndDeleteImage",
            "summary": "Busca\u0020y\u0020elimina\u0020una\u0020imagen\u0020existente\u0020con\u0020un\u0020nombre\u0020y\u0020directorio\u0020especificados.",
            "url": "classes/App-Http-Controllers-StorageController.html#method_findAndDeleteImage"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\StorageController\u003A\u003AdeleteDirectory\u0028\u0029",
            "name": "deleteDirectory",
            "summary": "Elimina\u0020un\u0020directorio\u0020especificado\u0020y\u0020su\u0020contenido.",
            "url": "classes/App-Http-Controllers-StorageController.html#method_deleteDirectory"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UsuarioController",
            "name": "UsuarioController",
            "summary": "Controlador\u0020para\u0020gestionar\u0020la\u0020autenticaci\u00F3n\u0020de\u0020usuarios.",
            "url": "classes/App-Http-Controllers-UsuarioController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UsuarioController\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "Controla\u0020el\u0020proceso\u0020de\u0020inicio\u0020de\u0020sesi\u00F3n\u0020de\u0020los\u0020usuarios\u0020y\u0020redirige\u0020a\u0020los\u0020usuarios\u0020a\u0020diferentes\u0020\u00E1reas\u0020de\u0020la\u0020aplicaci\u00F3n\u0020seg\u00FAn\u0020su\u0020rol.",
            "url": "classes/App-Http-Controllers-UsuarioController.html#method_authenticate"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\UsuarioController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "Desconecta\u0020a\u0020un\u0020usuario\u0020y\u0020lo\u0020redirige\u0020a\u0020la\u0020p\u00E1gina\u0020de\u0020inicio.",
            "url": "classes/App-Http-Controllers-UsuarioController.html#method_logout"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController",
            "name": "VehiculoController",
            "summary": "Controlador\u0020para\u0020gestionar\u0020los\u0020veh\u00EDculos.",
            "url": "classes/App-Http-Controllers-VehiculoController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003Amostrar\u0028\u0029",
            "name": "mostrar",
            "summary": "Muestra\u0020la\u0020p\u00E1gina\u0020con\u0020los\u0020detalles\u0020de\u0020un\u0020veh\u00EDculo\u0020espec\u00EDfico.",
            "url": "classes/App-Http-Controllers-VehiculoController.html#method_mostrar"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Muestra\u0020la\u0020lista\u0020de\u0020veh\u00EDculos\u0020con\u0020paginaci\u00F3n,\u0020limitando\u0020los\u0020resultados\u0020a\u002010.",
            "url": "classes/App-Http-Controllers-VehiculoController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Muestra\u0020el\u0020formulario\u0020para\u0020crear\u0020un\u0020nuevo\u0020veh\u00EDculo.",
            "url": "classes/App-Http-Controllers-VehiculoController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Guarda\u0020un\u0020nuevo\u0020veh\u00EDculo\u0020en\u0020la\u0020base\u0020de\u0020datos.",
            "url": "classes/App-Http-Controllers-VehiculoController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Muestra\u0020el\u0020formulario\u0020para\u0020editar\u0020un\u0020veh\u00EDculo.",
            "url": "classes/App-Http-Controllers-VehiculoController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Actualiza\u0020el\u0020veh\u00EDculo\u0020en\u0020la\u0020base\u0020de\u0020datos\u0020con\u0020los\u0020datos\u0020enviados.",
            "url": "classes/App-Http-Controllers-VehiculoController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Elimina\u0020el\u0020veh\u00EDculo\u0020de\u0020la\u0020base\u0020de\u0020datos.",
            "url": "classes/App-Http-Controllers-VehiculoController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\VehiculoController\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Busca\u0020los\u0020veh\u00EDculos\u0020que\u0020cumplen\u0020con\u0020los\u0020par\u00E1metros\u0020especificados.",
            "url": "classes/App-Http-Controllers-VehiculoController.html#method_search"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\Authenticate",
            "name": "Authenticate",
            "summary": "",
            "url": "classes/App-Http-Middleware-Authenticate.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\Authenticate\u003A\u003AredirectTo\u0028\u0029",
            "name": "redirectTo",
            "summary": "Verifica\u0020inicio\u0020de\u0020sesi\u00F3n.",
            "url": "classes/App-Http-Middleware-Authenticate.html#method_redirectTo"
        },                {
            "fqsen": "\\App\\Models\\Alquiler",
            "name": "Alquiler",
            "summary": "Modelo\u0020de\u0020Eloquent\u0020para\u0020la\u0020entidad\u0020Alquiler.",
            "url": "classes/App-Models-Alquiler.html"
        },                {
            "fqsen": "\\App\\Models\\Alquiler\u003A\u003Acliente\u0028\u0029",
            "name": "cliente",
            "summary": "Relaci\u00F3n\u0020con\u0020el\u0020modelo\u0020Cliente.",
            "url": "classes/App-Models-Alquiler.html#method_cliente"
        },                {
            "fqsen": "\\App\\Models\\Alquiler\u003A\u003Avehiculo\u0028\u0029",
            "name": "vehiculo",
            "summary": "Relaci\u00F3n\u0020con\u0020el\u0020modelo\u0020Veh\u00EDculo.",
            "url": "classes/App-Models-Alquiler.html#method_vehiculo"
        },                {
            "fqsen": "\\App\\Models\\Alquiler\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "Deshabilita\u0020los\u0020timestamps\u0020de\u0020Eloquent\u0020para\u0020este\u0020modelo.",
            "url": "classes/App-Models-Alquiler.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Alquiler\u003A\u003A\u0024table",
            "name": "table",
            "summary": "Nombre\u0020de\u0020la\u0020tabla\u0020asociada\u0020a\u0020este\u0020modelo.",
            "url": "classes/App-Models-Alquiler.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Alquiler\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "Atributos\u0020que\u0020se\u0020pueden\u0020asignar\u0020de\u0020forma\u0020masiva.",
            "url": "classes/App-Models-Alquiler.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Cliente",
            "name": "Cliente",
            "summary": "Modelo\u0020de\u0020Eloquent\u0020para\u0020la\u0020entidad\u0020Cliente.",
            "url": "classes/App-Models-Cliente.html"
        },                {
            "fqsen": "\\App\\Models\\Cliente\u003A\u003Ausuario\u0028\u0029",
            "name": "usuario",
            "summary": "Relaci\u00F3n\u0020morf\u0020con\u0020el\u0020modelo\u0020Usuario.",
            "url": "classes/App-Models-Cliente.html#method_usuario"
        },                {
            "fqsen": "\\App\\Models\\Cliente\u003A\u003A\u0024table",
            "name": "table",
            "summary": "Nombre\u0020de\u0020la\u0020tabla\u0020asociada\u0020a\u0020este\u0020modelo.",
            "url": "classes/App-Models-Cliente.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Cliente\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "Deshabilita\u0020los\u0020timestamps\u0020de\u0020Eloquent\u0020para\u0020este\u0020modelo.",
            "url": "classes/App-Models-Cliente.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Cliente\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "Atributos\u0020que\u0020se\u0020pueden\u0020asignar\u0020de\u0020forma\u0020masiva.",
            "url": "classes/App-Models-Cliente.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Empleado",
            "name": "Empleado",
            "summary": "Modelo\u0020de\u0020Eloquent\u0020para\u0020la\u0020entidad\u0020Empleado.",
            "url": "classes/App-Models-Empleado.html"
        },                {
            "fqsen": "\\App\\Models\\Empleado\u003A\u003Ausuario\u0028\u0029",
            "name": "usuario",
            "summary": "Relaci\u00F3n\u0020morf\u0020con\u0020el\u0020modelo\u0020Usuario.",
            "url": "classes/App-Models-Empleado.html#method_usuario"
        },                {
            "fqsen": "\\App\\Models\\Empleado\u003A\u003A\u0024table",
            "name": "table",
            "summary": "Nombre\u0020de\u0020la\u0020tabla\u0020asociada\u0020a\u0020este\u0020modelo.",
            "url": "classes/App-Models-Empleado.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Empleado\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "Deshabilita\u0020los\u0020timestamps\u0020de\u0020Eloquent\u0020para\u0020este\u0020modelo.",
            "url": "classes/App-Models-Empleado.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Empleado\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "Atributos\u0020que\u0020se\u0020pueden\u0020asignar\u0020de\u0020forma\u0020masiva.",
            "url": "classes/App-Models-Empleado.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Usuario",
            "name": "Usuario",
            "summary": "Modelo\u0020Usuario.",
            "url": "classes/App-Models-Usuario.html"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003AsetPasswordAttribute\u0028\u0029",
            "name": "setPasswordAttribute",
            "summary": "Establece\u0020y\u0020cifra\u0020la\u0020contrase\u00F1a\u0020del\u0020usuario.",
            "url": "classes/App-Models-Usuario.html#method_setPasswordAttribute"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003Autenteable\u0028\u0029",
            "name": "utenteable",
            "summary": "Relaci\u00F3n\u0020morfol\u00F3gica\u0020que\u0020llama\u0020al\u0020modelo\u0020relacionado\u0020\u0028Cliente\u0020o\u0020Empleado\u0029.",
            "url": "classes/App-Models-Usuario.html#method_utenteable"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "Indica\u0020si\u0020se\u0020deben\u0020guardar\u0020las\u0020marcas\u0020de\u0020tiempo\u0020en\u0020la\u0020tabla.",
            "url": "classes/App-Models-Usuario.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003A\u0024table",
            "name": "table",
            "summary": "Nombre\u0020de\u0020la\u0020tabla\u0020asociada\u0020a\u0020este\u0020modelo.",
            "url": "classes/App-Models-Usuario.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "Los\u0020atributos\u0020que\u0020se\u0020pueden\u0020asignar\u0020en\u0020masa.",
            "url": "classes/App-Models-Usuario.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "Los\u0020atributos\u0020que\u0020deben\u0020ocultarse\u0020en\u0020las\u0020serializaciones.",
            "url": "classes/App-Models-Usuario.html#property_hidden"
        },                {
            "fqsen": "\\App\\Models\\Vehiculo",
            "name": "Vehiculo",
            "summary": "Modelo\u0020Vehiculo.",
            "url": "classes/App-Models-Vehiculo.html"
        },                {
            "fqsen": "\\App\\Models\\Vehiculo\u003A\u003Aalquiler\u0028\u0029",
            "name": "alquiler",
            "summary": "Define\u0020la\u0020relaci\u00F3n\u0020de\u0020uno\u0020a\u0020muchos\u0020con\u0020el\u0020modelo\u0020Alquiler.",
            "url": "classes/App-Models-Vehiculo.html#method_alquiler"
        },                {
            "fqsen": "\\App\\Models\\Vehiculo\u003A\u003A\u0024table",
            "name": "table",
            "summary": "La\u0020tabla\u0020asociada\u0020a\u0020este\u0020modelo.",
            "url": "classes/App-Models-Vehiculo.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Vehiculo\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "Los\u0020atributos\u0020que\u0020se\u0020pueden\u0020asignar\u0020en\u0020masa.",
            "url": "classes/App-Models-Vehiculo.html#property_fillable"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider",
            "name": "AppServiceProvider",
            "summary": "La\u0020Pol\u00EDtica\u0020de\u0020Roles\u0020de\u0020autenticaci\u00F3n\u0020de\u0020la\u0020aplicaci\u00F3n.",
            "url": "classes/App-Providers-AppServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Inicializador\u0020de\u0020autenticaci\u00F3n.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003A\u0024policies",
            "name": "policies",
            "summary": "Las\u0020pol\u00EDticas\u0020de\u0020la\u0020aplicaci\u00F3n.",
            "url": "classes/App-Providers-AppServiceProvider.html#property_policies"
        },                {
            "fqsen": "\\Database\\Factories\\ClienteFactory",
            "name": "ClienteFactory",
            "summary": "",
            "url": "classes/Database-Factories-ClienteFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\ClienteFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020el\u0020estado\u0020predeterminado\u0020del\u0020modelo\u0020de\u0020cliente.",
            "url": "classes/Database-Factories-ClienteFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\EmpleadoFactory",
            "name": "EmpleadoFactory",
            "summary": "",
            "url": "classes/Database-Factories-EmpleadoFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\EmpleadoFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020el\u0020estado\u0020predeterminado\u0020del\u0020modelo\u0020de\u0020empleado.",
            "url": "classes/Database-Factories-EmpleadoFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\UsuarioFactory",
            "name": "UsuarioFactory",
            "summary": "",
            "url": "classes/Database-Factories-UsuarioFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\UsuarioFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020el\u0020estado\u0020predeterminado\u0020del\u0020modelo\u0020de\u0020usuario.",
            "url": "classes/Database-Factories-UsuarioFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\VehiculoFactory",
            "name": "VehiculoFactory",
            "summary": "",
            "url": "classes/Database-Factories-VehiculoFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\VehiculoFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020el\u0020estado\u0020predeterminado\u0020del\u0020modelo\u0020de\u0020veh\u00EDculo.",
            "url": "classes/Database-Factories-VehiculoFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder",
            "name": "DatabaseSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-DatabaseSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Seed\u0020the\u0020application\u0027s\u0020database.",
            "url": "classes/Database-Seeders-DatabaseSeeder.html#method_run"
        },                {
            "fqsen": "\\LARAVEL_START",
            "name": "LARAVEL_START",
            "summary": "",
            "url": "namespaces/default.html#constant_LARAVEL_START"
        },                {
            "fqsen": "\\Tests\\Feature\\DatabaseMigrationTest",
            "name": "DatabaseMigrationTest",
            "summary": "",
            "url": "classes/Tests-Feature-DatabaseMigrationTest.html"
        },                {
            "fqsen": "\\Tests\\Feature\\DatabaseMigrationTest\u003A\u003Aall_tables_are_created\u0028\u0029",
            "name": "all_tables_are_created",
            "summary": "",
            "url": "classes/Tests-Feature-DatabaseMigrationTest.html#method_all_tables_are_created"
        },                {
            "fqsen": "\\Tests\\Feature\\ExampleTest",
            "name": "ExampleTest",
            "summary": "",
            "url": "classes/Tests-Feature-ExampleTest.html"
        },                {
            "fqsen": "\\Tests\\Feature\\ExampleTest\u003A\u003Atest_the_application_returns_a_successful_response\u0028\u0029",
            "name": "test_the_application_returns_a_successful_response",
            "summary": "A\u0020basic\u0020test\u0020example.",
            "url": "classes/Tests-Feature-ExampleTest.html#method_test_the_application_returns_a_successful_response"
        },                {
            "fqsen": "\\Tests\\TestCase",
            "name": "TestCase",
            "summary": "",
            "url": "classes/Tests-TestCase.html"
        },                {
            "fqsen": "\\Tests\\Unit\\EloquentRelationshipsTest",
            "name": "EloquentRelationshipsTest",
            "summary": "",
            "url": "classes/Tests-Unit-EloquentRelationshipsTest.html"
        },                {
            "fqsen": "\\Tests\\Unit\\EloquentRelationshipsTest\u003A\u003Aa_vehicle_can_have_many_rentals\u0028\u0029",
            "name": "a_vehicle_can_have_many_rentals",
            "summary": "",
            "url": "classes/Tests-Unit-EloquentRelationshipsTest.html#method_a_vehicle_can_have_many_rentals"
        },                {
            "fqsen": "\\Tests\\Unit\\EloquentRelationshipsTest\u003A\u003Aa_rental_belongs_to_a_vehicle\u0028\u0029",
            "name": "a_rental_belongs_to_a_vehicle",
            "summary": "",
            "url": "classes/Tests-Unit-EloquentRelationshipsTest.html#method_a_rental_belongs_to_a_vehicle"
        },                {
            "fqsen": "\\Tests\\Unit\\EloquentRelationshipsTest\u003A\u003Aa_rental_belongs_to_a_client\u0028\u0029",
            "name": "a_rental_belongs_to_a_client",
            "summary": "",
            "url": "classes/Tests-Unit-EloquentRelationshipsTest.html#method_a_rental_belongs_to_a_client"
        },                {
            "fqsen": "\\Tests\\Unit\\UsuarioTest",
            "name": "UsuarioTest",
            "summary": "",
            "url": "classes/Tests-Unit-UsuarioTest.html"
        },                {
            "fqsen": "\\Tests\\Unit\\UsuarioTest\u003A\u003Ait_can_create_and_save_a_usuario\u0028\u0029",
            "name": "it_can_create_and_save_a_usuario",
            "summary": "",
            "url": "classes/Tests-Unit-UsuarioTest.html#method_it_can_create_and_save_a_usuario"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware",
            "name": "Middleware",
            "summary": "",
            "url": "namespaces/app-http-middleware.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\App\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/app-providers.html"
        },                {
            "fqsen": "\\Database\\Factories",
            "name": "Factories",
            "summary": "",
            "url": "namespaces/database-factories.html"
        },                {
            "fqsen": "\\Database",
            "name": "Database",
            "summary": "",
            "url": "namespaces/database.html"
        },                {
            "fqsen": "\\Database\\Seeders",
            "name": "Seeders",
            "summary": "",
            "url": "namespaces/database-seeders.html"
        },                {
            "fqsen": "\\Tests\\Feature",
            "name": "Feature",
            "summary": "",
            "url": "namespaces/tests-feature.html"
        },                {
            "fqsen": "\\Tests",
            "name": "Tests",
            "summary": "",
            "url": "namespaces/tests.html"
        },                {
            "fqsen": "\\Tests\\Unit",
            "name": "Unit",
            "summary": "",
            "url": "namespaces/tests-unit.html"
        }            ]
);
